# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  pgl:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - pgl-password
    volumes:
      - pgl-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=denpro
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgl-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "denpro"]
      interval: 10s
      timeout: 5s
      retries: 3
  rls:
    build:
      context: .
      dockerfile: Dockerfile.rls
    depends_on:
      pgl:
        condition: service_healthy
    secrets:
      - pgl-password
      - rls-credentials
    environment:
      - DENPRO_DATABASE_HOST=pgl
      - DENPRO_DATABASE_PASSWORD_FILE=/run/secrets/pgl-password
      - DENPRO_SSR_HOST=ssr
      - RAILS_DO_NOT_FORCE_SSL=true
      - RAILS_CREDENTIALS_KEY_FILE=/run/secrets/rls-credentials
      - THRUSTER_HTTP_PORT=8080
    # command: ["./bin/rails", "server"]
    ports:
      - 3000:3000
      - 8080:8080
    # expose:
    #   - 3000
    #   - 8080
    volumes:
      - rls-thruster-storage:/rails/storage/thruster
    healthcheck:
      test: ["CMD", "curl", "--request", "HEAD", "--silent", "--fail", "http://localhost:3000/up"]
      interval: 10s
      timeout: 5s
      retries: 3
  ssr:
    build:
      context: .
      dockerfile: Dockerfile.ssr
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5173/up"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5173:5173
volumes:
  pgl-data:
  rls-thruster-storage:
secrets:
  pgl-password:
    file: .compose/secrets/pgl-password.txt
  rls-credentials:
    file: config/credentials/production.key
