import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, relative, sep } from 'node:path'

const COMPONENTS_DIR = resolve('app/frontend/components')
const OUT_FILE = resolve('app/frontend/entrypoints/__ssr_imports__.ts')
const SOURCE_DIR = '/app/frontend'

type FileEntry = { relPath: string; key: string }

function findComponentFiles(dir: string, subdir: string): FileEntry[] {
  const fullDir = resolve(dir, subdir)
  if (!existsSync(fullDir)) return []
  
  const results: FileEntry[] = []
  
  function walk(current: string) {
    const entries = readdirSync(current, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = resolve(current, entry.name)
      if (entry.isDirectory()) {
        walk(fullPath)
      } else if (entry.isFile() && /\.([jt]sx)$/.test(entry.name)) {
        const rel = relative(COMPONENTS_DIR, fullPath)
        const noExt = rel.replace(/\.([jt]sx)$/, '')
        results.push({
          relPath: relative(dir, fullPath),
          key: `${SOURCE_DIR}/components/${noExt}`,
        })
      }
    }
  }
  
  walk(fullDir)
  return results
}

function generate(): string {
  const allFiles = findComponentFiles(COMPONENTS_DIR, '.')
  const appFiles = allFiles.filter((f) => f.key.includes('/components/app/'))
  const demosFiles = allFiles.filter((f) => f.key.includes('/components/demos/'))
  
  const imports: string[] = []
  const allEntries: string[] = []
  const appEntries: string[] = []
  const demosEntries: string[] = []
  let counter = 0
  
  for (const file of allFiles) {
    const varName = `__c${counter++}`
    imports.push(`import * as ${varName} from '@/components/${file.relPath}'`)
    
    const tsEntry = `  '${file.key}.tsx': ${varName} as any,`
    const jsEntry = `  '${file.key}.jsx': ${varName} as any,`
    allEntries.push(tsEntry, jsEntry)
    
    if (file.key.includes('/components/app/')) {
      appEntries.push(tsEntry, jsEntry)
    } else if (file.key.includes('/components/demos/')) {
      demosEntries.push(tsEntry, jsEntry)
    }
  }
  
  return [
    '// Generated by scripts/build-ssr-imports.ts — do not edit',
    'import type { ComponentType } from "react"',
    '',
    ...imports,
    '',
    'export const __ssrComponents: Record<string, { default: ComponentType<any> }> = {',
    ...allEntries,
    '}',
    '',
    'export const __ssrComponentsApp: Record<string, { default: ComponentType<any> }> = {',
    ...appEntries,
    '}',
    '',
    'export const __ssrComponentsDemos: Record<string, { default: ComponentType<any> }> = {',
    ...demosEntries,
    '}',
    '',
  ].join('\n')
}

const content = generate()
const existing = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf-8') : ''

if (content !== existing) {
  writeFileSync(OUT_FILE, content, 'utf-8')
  console.log('Generated', OUT_FILE)
}
